// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CShidori.DataHandler;

namespace CShidori
{
    public partial class MLfuzzing
    {
        /// <summary>
        /// model input class for MLfuzzing.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"uuid")]
            public string Uuid { get; set; }

            [ColumnName(@"response")]
            public string Response { get; set; }

            [ColumnName(@"request")]
            public string Request { get; set; }

            [ColumnName(@"vulnerable")]
            public string Vulnerable { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLfuzzing.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"MachineLearning\MLfuzzing.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
